### ISSUE TITLE
IMAGE attachment for more detail about items

### ISSUE THREAD

**Issue by Kashifayub89** [technbuzz/kharchay#5]
need to add one image for more details such if someone eat something they want to add along with the note section or buy a t shirt so user can ada small size image to it for more details.
about:blan
![whatsapp image 2018-06-18 at 5 17 08 pm](https://user-images.githubusercontent.com/39969564/41538335-2e29d9be-731c-11e8-9e85-c3312c4f4a6c.jpeg)
k

**Comment by technbuzz** [comment]
In order to implement this feature we will also need to add the details view. I think here how the list view would look like.
![image](https://user-images.githubusercontent.com/1523391/41820468-6dcd55a2-77e3-11e8-9408-153f96b433ce.png)

and the half finished details would like.
![image](https://user-images.githubusercontent.com/1523391/41820485-9c054722-77e3-11e8-8ffc-70c7bd0f14cd.png)
